/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dang.gui;

import dang.dao.TblCategoriesDAO;
import dang.dao.TblProductsDAO;
import dang.dto.CategoryFullModel;
import dang.dto.ProductFullModel;
import dang.dto.TblCategoriesDTO;
import dang.dto.TblProductsDTO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JDialog {

    TblCategoriesDAO categories;
    CategoryFullModel categoryFullModel;
    TblProductsDAO products;
    ProductFullModel productFullModel;
    boolean addNewCategory = true;
    boolean addNewProduct = true;

    /**
     * Creates new form MainForm
     *
     * @param parent
     * @param modal
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public MainForm(java.awt.Frame parent, boolean modal) throws SQLException, ClassNotFoundException {
        super(parent, modal);
        initComponents();
        categories = new TblCategoriesDAO();
        categories.loadFromDB();
        categoryFullModel = new CategoryFullModel(categories);
        btnDeleteCate.setEnabled(false);
        btnSaveCate.setEnabled(false);
        btnDeleteProduct.setEnabled(false);
        btnSaveProduct.setEnabled(false);
        products = new TblProductsDAO();
        products.loadFromDB(categories);
        productFullModel = new ProductFullModel(products);
        setupModel();

    }

    public final void setupModel() {
        tblCategory.setModel(categoryFullModel);
        tblProducts.setModel(productFullModel);
        this.cbCategoryName.setModel(new DefaultComboBoxModel(categories));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCategoryID = new javax.swing.JTextField();
        txtCategoryName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        btnAddNewCate = new javax.swing.JButton();
        btnSaveCate = new javax.swing.JButton();
        btnDeleteCate = new javax.swing.JButton();
        lbCategoryID = new javax.swing.JLabel();
        lbCategoryName = new javax.swing.JLabel();
        lbDescription = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cbCategoryName = new javax.swing.JComboBox<>();
        btnAddNewProduct = new javax.swing.JButton();
        btnSaveProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        lbProductID = new javax.swing.JLabel();
        lbProductName = new javax.swing.JLabel();
        lbUnit = new javax.swing.JLabel();
        lbQuantity = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detailed part:"));

        jLabel1.setText("CategoryID");

        jLabel2.setText("CategoryName");

        jLabel3.setText("Description");

        btnAddNewCate.setText("Add New");
        btnAddNewCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCateActionPerformed(evt);
            }
        });

        btnSaveCate.setText("Save");
        btnSaveCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCateActionPerformed(evt);
            }
        });

        btnDeleteCate.setText("Delete");
        btnDeleteCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCateActionPerformed(evt);
            }
        });

        lbCategoryID.setForeground(new java.awt.Color(255, 0, 0));

        lbCategoryName.setForeground(new java.awt.Color(255, 0, 0));

        lbDescription.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAddNewCate)
                        .addGap(26, 26, 26)
                        .addComponent(btnSaveCate)
                        .addGap(26, 26, 26)
                        .addComponent(btnDeleteCate, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbCategoryID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCategoryID)
                                .addComponent(txtCategoryName)
                                .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(lbCategoryName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCategoryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCategoryID)
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbCategoryName)
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbDescription)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewCate)
                    .addComponent(btnSaveCate)
                    .addComponent(btnDeleteCate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Main Part:"));

        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategory);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Category", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Main Part:"));

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProducts);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detailed part:"));

        jLabel4.setText("Product ID:");

        jLabel5.setText("Product Name:");

        jLabel6.setText("Category Name:");

        jLabel7.setText("Unit: ");

        jLabel8.setText("Quantity: ");

        jLabel9.setText("Price: ");

        cbCategoryName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddNewProduct.setText("Add New");
        btnAddNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewProductActionPerformed(evt);
            }
        });

        btnSaveProduct.setText("Save");
        btnSaveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProductActionPerformed(evt);
            }
        });

        btnDeleteProduct.setText("Delete");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        lbProductID.setForeground(new java.awt.Color(255, 51, 51));

        lbProductName.setForeground(new java.awt.Color(255, 51, 51));

        lbUnit.setForeground(new java.awt.Color(255, 51, 51));

        lbQuantity.setForeground(new java.awt.Color(255, 51, 51));

        lbPrice.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnAddNewProduct)
                        .addGap(38, 38, 38)
                        .addComponent(btnSaveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbProductID)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProductID)
                                .addComponent(txtProductName)
                                .addComponent(txtUnit)
                                .addComponent(cbCategoryName, 0, 136, Short.MAX_VALUE)
                                .addComponent(txtQuantity)
                                .addComponent(txtPrice))
                            .addComponent(lbProductName)
                            .addComponent(lbUnit)
                            .addComponent(lbQuantity)
                            .addComponent(lbPrice))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lbProductID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lbProductName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lbUnit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(lbQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lbPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewProduct)
                    .addComponent(btnSaveProduct)
                    .addComponent(btnDeleteProduct))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Products", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        setLabelCategory();
        int pos = tblCategory.getSelectedRow();
        TblCategoriesDTO dto = categoryFullModel.getCategories().get(pos);
        txtCategoryID.setText(dto.getCategoryID());
        txtCategoryName.setText(dto.getCategoryName());
        txtDescription.setText(dto.getDescription());
        addNewCategory = false;
        txtCategoryID.setEditable(false);
        btnAddNewCate.setEnabled(false);
        btnDeleteCate.setEnabled(true);
        btnSaveCate.setEnabled(true);
    }//GEN-LAST:event_tblCategoryMouseClicked

    private void btnAddNewCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCateActionPerformed
        setLabelCategory();
        txtCategoryID.setText("");
        txtCategoryName.setText("");
        txtDescription.setText("");
        addNewCategory = true;
        txtCategoryID.setEditable(true);
        btnSaveCate.setEnabled(true);
    }//GEN-LAST:event_btnAddNewCateActionPerformed
    public boolean checkEmptyFieldCategory() {
        if (txtCategoryID.getText().trim().isEmpty()) {
            lbCategoryID.setText("Category ID must'n be empty");
            return true;
        } else if (txtCategoryName.getText().trim().isEmpty()) {
            lbCategoryID.setText("");
            lbCategoryName.setText("Category Name must'n be empty");
            return true;
        } else if (txtDescription.getText().trim().isEmpty()) {
            lbCategoryName.setText("");
            lbCategoryID.setText("");
            lbDescription.setText("Description must'n be empty");
            return true;
        }
        return false;
    }

    public void setLabelCategory() {
        lbCategoryID.setText("");
        lbCategoryName.setText("");
        lbDescription.setText("");
    }

    public void setTextFieldCategory() {
        txtCategoryID.setText("");
        txtCategoryName.setText("");
        txtDescription.setText("");
    }
    private void btnSaveCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCateActionPerformed
//      Kiểm tra các miền nhập dữ liệu của bảng category
        if (checkEmptyFieldCategory()) {
            return;
        }
        String categoryID = txtCategoryID.getText();
        String categoryName = txtCategoryName.getText();
        String description = txtDescription.getText();
        TblCategoriesDTO dto = new TblCategoriesDTO(categoryID, categoryName, description);
//      Kiểm tra trạng thái addNewCategory để thêm hoặc sửa
        if (addNewCategory) {
            try {
//      Add Category Function
//      Kiểm tra category trùng      
                boolean duplicateCate = categories.findCategory(categoryID);
                if (duplicateCate) {
                    JOptionPane.showMessageDialog(this, "Duplicate categoryID");
                } else {
                    boolean rsInsert = categories.insertCategory(dto);
                    if (rsInsert) {
                        categoryFullModel.getCategories().add(dto);
                        tblCategory.updateUI();
                        setTextFieldCategory();
                        btnSaveCate.setEnabled(false);
                        setLabelCategory();
                        JOptionPane.showMessageDialog(this, "Date save");
                    } else {
                        JOptionPane.showMessageDialog(this, "Can't Save");
                    }
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
//      Update function
                boolean rsUpdate = categories.updateCategory(categoryID, categoryName, description);
                if (rsUpdate) {
                    int rowSelect = tblCategory.getSelectedRow();
//      sửa các miền nhập của category thành ""
                    setTextFieldCategory();
//      sửa các label cảnh báo category lại thành ""
                    setLabelCategory();
                    btnAddNewCate.setEnabled(true);
                    btnSaveCate.setEnabled(false);
                    btnDeleteCate.setEnabled(false);
                    txtCategoryID.setEditable(true);
//      sửa lại dữ liệu trong bảng model
                    categoryFullModel.getCategories().set(rowSelect, dto);
//      Cập nhật lại thông tin trong bảng cate
                    tblCategory.updateUI();
                    JOptionPane.showMessageDialog(this, "Data save");
                } else {
                    JOptionPane.showMessageDialog(this, "can't save");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            addNewCategory = true;
        }
    }//GEN-LAST:event_btnSaveCateActionPerformed

    private void btnDeleteCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCateActionPerformed
        String categoryID = txtCategoryID.getText();
        int rsChoice = JOptionPane.showConfirmDialog(this, "Do you want to delete " + categoryID, "Yes/No", JOptionPane.YES_NO_OPTION);
        if (rsChoice == JOptionPane.YES_OPTION) {
            boolean rsDelete;
            try {
//      Delete Function
                if (!addNewCategory) {
//      Kiểm tra category có chứa product nào không
                    boolean checkCategory = products.findProduct(categoryID);
                    if (checkCategory) {
                        JOptionPane.showMessageDialog(this, "Please delete product which contain this category first");
                        return;
                    } else {
                        int selectRow = tblCategory.getSelectedRow();
                        rsDelete = categories.deleteCategory(categoryID);
                        if (rsDelete) {
                            categoryFullModel.getCategories().remove(selectRow);
                            tblCategory.updateUI();
                            btnAddNewCate.setEnabled(true);
                            btnDeleteCate.setEnabled(false);
                            btnSaveCate.setEnabled(false);
                            txtCategoryID.setEditable(true);
//      Cập nhật miền nhập category thành "" 
                            setTextFieldCategory();
                            JOptionPane.showMessageDialog(this, "Delete successfully !!");
                        } else {
                            JOptionPane.showMessageDialog(this, "Can't delete");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Can't delete");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            addNewCategory = true;
        }
    }//GEN-LAST:event_btnDeleteCateActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
        int row = tblProducts.getSelectedRow();
        TblProductsDTO dto = productFullModel.getProducts().get(row);
        txtProductID.setText(dto.getProductID());
        txtProductName.setText(dto.getProductName());
        txtUnit.setText(dto.getUnit());
        txtPrice.setText("" + dto.getPrice());
        txtQuantity.setText("" + dto.getQuantity());
        int index = categories.findCate(dto.getCategory().getCategoryID());
        cbCategoryName.setSelectedIndex(index);
        addNewProduct = false;
        btnDeleteProduct.setEnabled(true);
        btnSaveProduct.setEnabled(true);
        btnAddNewProduct.setEnabled(false);
        txtProductID.setEditable(false);
        setLabelProduct();
    }//GEN-LAST:event_tblProductsMouseClicked

    private void btnAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewProductActionPerformed
        txtProductID.setText("");
        txtProductName.setText("");
        txtQuantity.setText("");
        txtUnit.setText("");
        txtPrice.setText("");
        addNewProduct = true;
        txtProductID.setEditable(true);
        btnSaveProduct.setEnabled(true);
    }//GEN-LAST:event_btnAddNewProductActionPerformed
    public boolean checkEmptyFieldProduct() {
        if (txtProductID.getText().trim().isEmpty()) {
            lbProductID.setText("Product ID musn't be empty");
            return true;
        } else if (txtProductName.getText().trim().isEmpty()) {
            lbProductID.setText("");
            lbProductName.setText("Product Name must'n be empty");
            return true;
        } else if (txtUnit.getText().trim().isEmpty()) {
            lbProductID.setText("");
            lbProductName.setText("");
            lbUnit.setText("Unit must'n be empty");
            return true;
        } else if (txtQuantity.getText().trim().isEmpty()) {
            lbProductID.setText("");
            lbProductName.setText("");
            lbUnit.setText("");
            lbQuantity.setText("Quantity must't be empty");
            return true;
        } else if (txtPrice.getText().trim().isEmpty()) {
            lbProductID.setText("");
            lbProductName.setText("");
            lbUnit.setText("");
            lbQuantity.setText("");
            lbPrice.setText("Price must'n be empty");
            return true;
        }
        return false;
    }

    public void setLabelProduct() {
        lbProductID.setText("");
        lbProductName.setText("");
        lbUnit.setText("");
        lbPrice.setText("");
        lbQuantity.setText("");
    }

    public void setTextFieldProduct() {
        txtProductID.setText("");
        txtProductName.setText("");
        txtQuantity.setText("");
        txtUnit.setText("");
        txtPrice.setText("");
    }
    private void btnSaveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProductActionPerformed
//      Kiểm tra thông tin người dùng nhập ở product
        if (checkEmptyFieldProduct()) {
            return;
        }
        String productID = txtProductID.getText();
        String productName = txtProductName.getText();
        String unit = txtUnit.getText();        
        float price = 0;
        int quantity = 0;
//      Kiểm tra điều kiện nhập quantity
        try {            
            quantity = Integer.parseInt(txtQuantity.getText());
        } catch (NumberFormatException e) {
            lbQuantity.setText("Quantity must be integer");            
            return;
        }
//      Kiểm tra điều kiện nhập price
        try {
            price = Float.parseFloat(txtPrice.getText());
        } catch (NumberFormatException e) {
            lbQuantity.setText("");
            lbPrice.setText("Price must be float");
            return;
        }
        
        TblCategoriesDTO category = (TblCategoriesDTO) cbCategoryName.getSelectedItem();
        TblProductsDTO dto = new TblProductsDTO(productID, productName, unit, price, quantity, category);
//      Kiểm tra trạng thái của addNewProduct để thêm product hay update Product
        if (addNewProduct) {
//      Add new Product function
            try {
                boolean rsAddProduct = products.insertProduct(dto);
                if (rsAddProduct) {
                    productFullModel.getProducts().add(dto);
                    tblProducts.updateUI();
//      Cập nhật miền nhập product thành ""                  
                    setTextFieldProduct();
//      Cập nhật label product thành ""                  
                    setLabelProduct();
                    JOptionPane.showMessageDialog(this, "Data save");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
//      Update product function
                boolean rsUpdateProduct = products.updateProduct(dto);
                if (rsUpdateProduct) {
                    int selectRow = tblProducts.getSelectedRow();
//      Cập nhật miền nhập product thành ""
                    setTextFieldProduct();
//      Cập nhật label product thành ""
                    setLabelProduct();
                    txtProductID.setEditable(true);
                    btnDeleteProduct.setEnabled(false);
                    btnSaveProduct.setEnabled(false);
                    btnAddNewProduct.setEnabled(true);
                    productFullModel.getProducts().set(selectRow, dto);
                    tblProducts.updateUI();
                    JOptionPane.showMessageDialog(this, "Data save");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        addNewProduct = true;
    }//GEN-LAST:event_btnSaveProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        if (!addNewProduct) {
            String productID = txtProductID.getText();
            int choice = JOptionPane.showConfirmDialog(this, "Do you want to delete " + productID, "YES/NO", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                int selectRow = tblProducts.getSelectedRow();
                try {
//      Delete Product Function
                    boolean rsDelete = products.deleteProducts(productID);
                    if (rsDelete) {
                        productFullModel.getProducts().remove(selectRow);
                        tblProducts.updateUI();
//      Cập nhật miền nhập product thành ""                        
                        setTextFieldProduct();
                        txtProductID.setEditable(true);
                        btnAddNewProduct.setEnabled(true);
                        btnDeleteProduct.setEnabled(false);
                        btnSaveProduct.setEnabled(false);
                        JOptionPane.showMessageDialog(this, "Delete Successfully !!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Delete failed !!");
                    }
                    addNewProduct = true;
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainForm dialog = null;
                try {
                    dialog = new MainForm(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCate;
    private javax.swing.JButton btnAddNewProduct;
    private javax.swing.JButton btnDeleteCate;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnSaveCate;
    private javax.swing.JButton btnSaveProduct;
    private javax.swing.JComboBox<String> cbCategoryName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCategoryID;
    private javax.swing.JLabel lbCategoryName;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbProductID;
    private javax.swing.JLabel lbProductName;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbUnit;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtCategoryID;
    private javax.swing.JTextField txtCategoryName;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
